apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
  - name: app
    image: gcr.io/quantum-petal-405619/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8000
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      periodSeconds: 2
      initialDelaySeconds: 0
      failureThreshold: 3
      successThreshold: 1
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3